### ISSUE TITLE
What is the email address for login?

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/pgadmin_ynh#2]
The login page require the email address to login. I tried to login address of admin username which was given at the installation of app. But it don't work. 
Is there any other username credential, I have to enter to login?

**Comment by Josue-T** [comment]
Hello,

Sorry mybe it's not really documented. The username is : user@domain.tld

**Comment by anmol26s** [comment]
You mean the the account given at the time of installations' email address along with password or the LDAP user?

**Comment by Josue-T** [comment]
No the user that you give at the install.

This app have no link with LDAP.

**Comment by anmol26s** [comment]
I am trying to login with the admin email address and the password given while installation, but its not working.

**Comment by Josue-T** [comment]
Did you add any special char in the password ?
Normally the user is : `user_that_you_said_at_the_install@domain.tld`
Password : `password_that_you_said_at_the_install`
And it should work.

If not could you try maybe to reinstall the app ? And / or maybe have you any log of the install ?

**Comment by anmol26s** [comment]
Hi
I got the issue. The username should be the primary email of the user given at the time of installation.
i.e if `user_given_at_installation@primary_domain.tld`.
This will work when the app is installed on `primary_domain.tld/pgadmin`. But when the app is installed on a sub-domain like **pgadmin.primary_domain.tld** the username becomes `user_given_at_installation@pgadmin.primary_domain.tld` which is not correct email for the user.
The admin email should be called by **email=$(ynh_user_get_info $admin 'mail')**  and this **$email** should be used rather then **$admin@$domain** here https://github.com/YunoHost-Apps/pgadmin_ynh/blob/master/scripts/install#L78.

Correct : 
 `../conf/setup.exp "$final_path/bin/python2.7" "$final_path/lib/python2.7/site-packages/pgadmin4/setup.py" "$email"
`
I hope I could make myself clear.

**Comment by Josue-T** [comment]
Thanks for your info.

Should be fixed by 7575a3e

I close this issue. If you have any other problem reopen it or create a new issue.

**Comment by zyphlar** [comment]
This issue is still confusing, it needs to be explicitly stated that the selected user's *email address* will be the pgadmin administrative login, and the *entered password* will be the administrative password, and that Yunohost SSO is not currently supported. Otherwise the assumption is that certain SSO users will have access to the app *and/or* they'll need to type the administrative password. The current arrangement is nonstandard and unexpected.
